consul:
  image: progrium/consul
  command: ["-server","-bootstrap","-ui-dir","/ui"]
  ports:
    - :53:53
    - :8300-8302:8300-8302
    - :8400:8400 
    - :8500:8500
registrator:
  image: gliderlabs/registrator:master
  links:
   - consul
  command: ["-internal=true","-retry-attempts=-1", "-retry-interval=1000", "consul://consul:8500"]
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
server-oltp:
  build: server
  links: 
    - platform
  environment:
    - MYSQL_ROOT_PASSWORD=secret
  ports:
    - :3306:3306
server-oltp-prom-mysqld:
  image: prom/mysqld-exporter
  links:
    - server-oltp:db
    - consul
  environment:
    - DATA_SOURCE_NAME=root:secret@tcp(db:3306)/sbtest
  ports:
    - :9104:9104
server-update:
  build: server
  links: 
    - platform
  environment:
    - MYSQL_ROOT_PASSWORD=secret
server-update-prom-mysqld:
  image: prom/mysqld-exporter
  links:
    - server-update:db
    - consul
  environment:
    - DATA_SOURCE_NAME=root:secret@tcp(db:3306)/sbtest
  ports:
    - :9105:9104
prom-node-exporter:
  image: prom/node-exporter
  ports:
    - :9100:9100
sysbench-oltp:
   build: sysbench
   links: 
    - server-oltp:db
   environment:
    - TXRATE=10
    - TEST=oltp
sysbench-update:
   build: sysbench
   links: 
    - server-update:db
   environment:
    - TXRATE=10
    - TEST=update_index
platform:
  build: platform
  links:
    - consul
  environment:
    - API_HOSTNAME=platform
    - NODE_IP=invalid
  ports:
    - :3000:3000
    - :8000:8000
    - :9001:9001
