percona-server-platform-1:
  build: server
  links: 
    - percona-platform:platform
  environment:
    - MYSQL_ROOT_PASSWORD=secret
  ports:
    - :3306:3306
percona-server-platform-2:
  build: server
  links: 
    - percona-platform:platform
  environment:
    - MYSQL_ROOT_PASSWORD=secret
sysbench-1:
   build: sysbench
   links: 
    - percona-server-platform-1:db
sysbench-2:
   build: sysbench
   links: 
    - percona-server-platform-2:db
percona-platform:
  image: percona/percona-platform
  environment:
    - API_HOSTNAME=platform
    - NODE_IP=percona-server-platform-1
  ports:
    - :3000:3000
    - :8000:8000
    - :9001:9001
