global:
 scrape_interval:     1s
 evaluation_interval: 1s

scrape_configs:
- job_name: 'overwritten-default'

  scrape_interval: 1s
  scrape_timeout:  1s

  consul_sd_configs:
  - server:   'consul:8500'
    services: ['mysqld-exporter']

  relabel_configs:
  - source_labels: ['__meta_consul_service']
    regex:         '(.*)'
    target_label:  'job'
    replacement:   '$1'
  - source_labels: ['__meta_consul_service_address','__meta_consul_service_port']
    regex:         '(.*);(.*)'
    target_label:  '__address__'
    replacement:   '$1:$2'
  - source_labels: ['__meta_consul_service_address']
    regex:         '(.*)'
    target_label:  'alias'
    replacement:   '$1'
  - source_labels: ['__meta_consul_service_address']
    regex:         '(.*)'
    target_label:  'instance'
    replacement:   '$1'
